name = "All the Mods 10"
author = "ATMTeam"
version = "6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09193a19f89ec61cdef8393a6d845b61c1bc71061d12a0d10291f0fb2bb3866e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
