name = "All the Mods 10"
author = "ATMTeam"
version = "6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e563bf1463beea983f43351c9ed893075774809b613d1a261ce7e85dd049ce5c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
